### ISSUE TITLE
ZkNoid Bounty №2: interactive gameplay videos

### ISSUE THREAD

**Issue by asimaranov** [ZkNoid/zknoid#13]
# Title:

ZkNoid Bounty №2: interactive gameplay videos

# Introduction:

ZkNoid provides a provably fair and trustworthy environment for next-generation gaming. Zero-knowledge-powered games allow the implementation of blockchain integrity verification mechanisms without the need for players to share their sensitive information. This brings forth many advantages to the realm of gaming:

- Fair gameplay. Every critical step of each game is powered by Zk-Proofs (ZKPs), guaranteeing that your experience is real: no bots, no cheats!
- Enhanced user security. Anonymous blockchain accounts reduce the risk of tracing to real-life identities and guard players from stalking or harassment.
- Lower Costs. ZKPs allow to overcome the restraints of network gas costs while retaining the high level of blockchain security.
- Boosted competitiveness. ZKP-based validations hide details about your gameplay, preserving personalized strategies, and facilitating exciting UX.
- Increased scalability. Private proofs minimize block space usage unlocking scaling that is critical for the future of web3 gaming.
- Censorship resistance. By validating actions using ZKPs, zkGames operate freely regardless of geographical location, resisting unfair political restrictions.

With ZkNoid, players can elevate their gaming experience with an ever-increasing assortment of fun and immersive games and earn valuable prizes and rewards in the process!

Let’s give it a go!

# Bounty Description:

Our second task within the Astromina platform is meant to be fun and interactive. We challenge you to demonstrate the UX of gamers on the ZkNoid platform by recording your gameplay on any one (or several) of our listed games:

- Arkanoid
- Checkers
- Lottery
- Tileville
- Randzu
- Thimblerig

To participate in the bounty, simply record your ZkNoid gaming journey with any screen recording software and send it to us. Be creative, using editing software is encouraged! Don’t forget to describe your experience in a comment to the submission.

If you wish to team up with a fellow community member to play a multiplayer game, join our [[Discord](https://discord.com/invite/aQt9HPZQ)](https://discord.com/invite/aQt9HPZQ), you can always find a skilled opponent there!

At the end of the contest, the team will watch all your submissions and pick the top 3 participants based on the UX features you demonstrate, the overall quality of your video, and the feedback you leave. Genuine feedback and improvement suggestions are welcome, our goal is to provide you with a smooth and entertaining experience!

We wish you to have a fun and immersive process =)

# Acceptance Criteria:

The criteria that must be met for the bounty to be considered complete:

- Your video must be in a horizontal format and at least 1080p.
- Be creative, interesting, useful, and fun.

# Bounty Reward:

- **Amount:** 600 $MINA
- **Distribution Method:**
    🥇 200 $MINA
    🥈 175 $MINA
    🥉 150 $MINA
    75 $MINA distributed among all other participants

# Deadline:

03.10.2024 23:59 GMT

# Submission Instructions:

Provide a video file and a description of your UX in markdown. Leave it as a comment for the issue.

# Additional Information:

Feel free to ask any questions in ZkNoid discord: https://discord.com/invite/aQt9HPZQ

Know more about ZkNoid in social networks

Twitter: https://x.com/ZkNoid
Blog: https://medium.com/@zknoid
Website: https://zknoid.io/
ZkApp: https://app.zknoid.io/
Docs: https://docs.zknoid.io/docs
GitHub: https://github.com/ZkNoid

# Notes:

- The reward will be distributed among all submissions
- Our team reserves the right to approve applications and reject a submission without explanation.
- Participants agree that their materials may be used in a blog article, YouTube video, and X (formerly Twitter) post.

**Comment by kotocryo** [comment]
I got a lot of positive emotions playing my favorite game since childhood. I like the design of the site, the bright colors and the gameplay itself is fun. A little work on optimizing the game in full screen and it will be great. Thanks to the development team for a second youth.
https://drive.google.com/drive/folders/17kfKos86LsGWv9HmXYVanKbvppZpwGVb?usp=drive_link

**Comment by MariaAlexsandrovna** [comment]
I played the games that I liked the most - Randzu and Tileville. Playing these games you completely relax and enjoy the process. The rules of the games are very simple, everyone will understand them. So I very advise you to play!!

https://drive.google.com/file/d/1_ajghLSqk7gRXbAh2Nch3DJ20sGaWIsG/view?usp=sharing

**Comment by RamanS1819** [comment]
I played almost all the games on this platform in with i used to play these two games most - Tileville and arkanoid . The games are really interactive and playing these games are really fun!!

https://drive.google.com/file/d/1y44fUKS_i9mM-j36PphnKZ6ev_yiizxJ/view?usp=sharing

**Comment by Kotoshroe** [comment]
Thanks ZkNoid for all that games it was definitely fun playing them ahaha 
I really like visual style of all games)) its magnificent 

https://drive.google.com/file/d/13ocDyZH3BpabmapB6ixGk-JxF8bYJZeF/view?usp=sharing
